source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.6', '>= 5.2.6.2'

# #1
group :production do
  gem 'pg'
  gem 'rails_12factor'
end

# #2
group :development do
  gem 'sqlite3'
end

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0', '>= 5.0.7'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2.2'
# Use jquery as the JavaScript library
gem 'jquery-rails', '>= 4.3.3'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# bootstrap is a css framework. Provides layouts,forms etc
gem 'bootstrap-sass'
# devise for sign in & sign out
gem 'devise', '>= 4.5.0'
#font-awesome
gem 'font-awesome-sass'
#faker seed gem
gem 'faker'
#omniauth for facebook
gem 'omniauth-facebook'
gem 'omniauth'
#sendgrid to deal with confirmations
gem 'sendgrid-ruby'
gem 'bootstrap', '~> 4.0.0.alpha6'
gem 'byebug'
gem 'activeadmin', '>= 1.3.1'

group :development, :test do
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'rspec-rails', '~> 3.8', '>= 3.8.0'
  gem 'factory_bot_rails', '>= 4.11.0'
end
